In [1]:
# prompt: connect with drive

from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [2]:

%cd /content/drive/MyDrive/product_classification


/content/drive/MyDrive/product_classification


In [3]:
!ls

marketing_sample_for_amazon_com-ecommerce__20200101_20200131__10k_data.csv  results


In [4]:

import pandas as pd
import numpy as np

In [5]:
df_product_classification = pd.read_csv('marketing_sample_for_amazon_com-ecommerce__20200101_20200131__10k_data.csv')
# Use pd.read_csv to read comma-separated value files.

In [6]:
# prompt: show first 10 rows

df_product_classification.head(3)


Uniq Id  \
0  4c69b61db1fc16e7013b43fc926e502d   
1  66d49bbed043f5be260fa9f7fbff5957   
2  2c55cae269aebf53838484b0d7dd931a   

                                        Product Name  Brand Name  Asin  \
0  DB Longboards CoreFlex Crossbow 41" Bamboo Fib...         NaN   NaN   
1  Electronic Snap Circuits Mini Kits Classpack, ...         NaN   NaN   
2  3Doodler Create Flexy 3D Printing Filament Ref...         NaN   NaN   

                                            Category Upc Ean Code  List Price  \
0  Sports & Outdoors | Outdoor Recreation | Skate...          NaN         NaN   
1  Toys & Games | Learning & Education | Science ...          NaN         NaN   
2          Toys & Games | Arts & Crafts | Craft Kits          NaN         NaN   

  Selling Price  Quantity Model Number  ...  \
0       $237.68       NaN          NaN  ...   
1        $99.95       NaN        55324  ...   
2        $34.99       NaN          NaN  ...   

                                         Product Url Stock Product Details  \
0  https://www.amazon.com/DB-Longboards-CoreFlex-...   NaN             NaN   
1  https://www.amazon.com/Electronic-Circuits-Cla...   NaN             NaN   
2  https://www.amazon.com/3Doodler-Plastic-Innova...   NaN             NaN   

  Dimensions Color Ingredients Direction To Use  Is Amazon Seller  \
0        NaN   NaN         NaN              NaN                 Y   
1        NaN   NaN         NaN              NaN                 Y   
2        NaN   NaN         NaN              NaN                 Y   

  Size Quantity Variant  Product Description  
0                   NaN                  NaN  
1                   NaN                  NaN  
2                   NaN                  NaN  

[3 rows x 28 columns]

In [7]:

# Checking Summary Statistics
df_product_classification.describe()

Brand Name  Asin  List Price  Quantity  Sku  Stock  Product Details  \
count         0.0   0.0         0.0       0.0  0.0    0.0              0.0   
mean          NaN   NaN         NaN       NaN  NaN    NaN              NaN   
std           NaN   NaN         NaN       NaN  NaN    NaN              NaN   
min           NaN   NaN         NaN       NaN  NaN    NaN              NaN   
25%           NaN   NaN         NaN       NaN  NaN    NaN              NaN   
50%           NaN   NaN         NaN       NaN  NaN    NaN              NaN   
75%           NaN   NaN         NaN       NaN  NaN    NaN              NaN   
max           NaN   NaN         NaN       NaN  NaN    NaN              NaN   

       Dimensions  Color  Ingredients  Direction To Use  \
count         0.0    0.0          0.0               0.0   
mean          NaN    NaN          NaN               NaN   
std           NaN    NaN          NaN               NaN   
min           NaN    NaN          NaN               NaN   
25%           NaN    NaN          NaN               NaN   
50%           NaN    NaN          NaN               NaN   
75%           NaN    NaN          NaN               NaN   
max           NaN    NaN          NaN               NaN   

       Size Quantity Variant  Product Description  
count                    0.0                  0.0  
mean                     NaN                  NaN  
std                      NaN                  NaN  
min                      NaN                  NaN  
25%                      NaN                  NaN  
50%                      NaN                  NaN  
75%                      NaN                  NaN  
max                      NaN                  NaN

In [8]:
# prompt: only want product name and category

df_product_classification = df_product_classification[['Product Name', 'Category']]
df_product_classification.head(3)


Product Name  \
0  DB Longboards CoreFlex Crossbow 41" Bamboo Fib...   
1  Electronic Snap Circuits Mini Kits Classpack, ...   
2  3Doodler Create Flexy 3D Printing Filament Ref...   

                                            Category  
0  Sports & Outdoors | Outdoor Recreation | Skate...  
1  Toys & Games | Learning & Education | Science ...  
2          Toys & Games | Arts & Crafts | Craft Kits

In [9]:
df_product_classification.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Product Name  10002 non-null  object
 1   Category      9172 non-null   object
dtypes: object(2)
memory usage: 156.4+ KB


In [10]:
# Checking NaN Values
df_product_classification.isnull().sum()

Product Name      0
Category        830
dtype: int64

In [11]:
# Filling NaN values with NumPy's NaN
df_product_classification.fillna(np.NaN)

Product Name  \
0      DB Longboards CoreFlex Crossbow 41" Bamboo Fib...   
1      Electronic Snap Circuits Mini Kits Classpack, ...   
2      3Doodler Create Flexy 3D Printing Filament Ref...   
3      Guillow Airplane Design Studio with Travel Cas...   
4                       Woodstock- Collage 500 pc Puzzle   
...                                                  ...   
9997   Remedia Publications REM536B Money Activity Bo...   
9998   Trends International NFL La Chargers HG - Mobi...   
9999   NewPath Learning 10 Piece Science Owls and Owl...   
10000           Disney Princess Do It Yourself Braid Set   
10001        Hasegawa Ladders Lucano Step Ladder, Orange   

                                                Category  
0      Sports & Outdoors | Outdoor Recreation | Skate...  
1      Toys & Games | Learning & Education | Science ...  
2              Toys & Games | Arts & Crafts | Craft Kits  
3      Toys & Games | Hobbies | Models & Model Kits |...  
4                Toys & Games | Puzzles | Jigsaw Puzzles  
...                                                  ...  
9997   Toys & Games | Learning & Education | Counting...  
9998                        Toys & Games | Arts & Crafts  
9999   Office Products | Office & School Supplies | E...  
10000          Toys & Games | Arts & Crafts | Craft Kits  
10001  Home & Kitchen | Furniture | Kids' Furniture |...  

[10002 rows x 2 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_product_classification['Category'] = label_encoder.fit_transform(df_product_classification['Category'])


In [13]:
# Save the mapping
category_to_label = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
label_to_category = dict(zip(label_encoder.transform(label_encoder.classes_), label_encoder.classes_))


In [39]:
# prompt: print category to label for cateogry 462

print(label_to_category[556])


Toys & Games | Arts & Crafts


In [15]:
df_product_classification.head(10)

Product Name  Category
0  DB Longboards CoreFlex Crossbow 41" Bamboo Fib...       462
1  Electronic Snap Circuits Mini Kits Classpack, ...       803
2  3Doodler Create Flexy 3D Printing Filament Ref...       560
3  Guillow Airplane Design Studio with Travel Cas...       682
4                   Woodstock- Collage 500 pc Puzzle       859
5  Terra by Battat – 4 Dinosaur Toys, Medium – Di...       938
6  Rubie's Child's Pokemon Deluxe Pikachu Costume...       101
7  Hoffmaster 120813 Double-Tipped Triangular Cra...       577
8  ARTSCAPE Etched Glass 24" x 36" Window Film, 2...       297
9  Pokemon TCG: Sun and Moon Crimson Invasion Eli...       938

In [16]:
from sklearn.model_selection import train_test_split

train_texts, val_texts, train_labels, val_labels = train_test_split(
   df_product_classification['Product Name'].tolist(),
    df_product_classification['Category'].tolist(),
    test_size=0.2,
    random_state=42
)


In [17]:
train_texts[:5]

['SunWorks Construction Paper, Turquoise, 9" x 12", 50 Sheets',
 'Delta Plush Toy w Sound',
 '3B Scientific U10351 Interferometer Accessory Kit',
 "Children's Factory Woodland Adapta-Benches Set of 3 Kids Table and Chairs Kids Furniture Classroom Furniture",
 'Aurora World Precious Moments Luffie Lamb, 8.5"']

In [18]:
# prompt: print shapes of both tain and text with labels

print(np.shape(train_texts), np.shape(train_labels))
print(np.shape(val_texts), np.shape(val_labels))


(8001,) (8001,)
(2001,) (2001,)


In [19]:
# prompt: install transforomers

!pip install transformers


In [20]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [21]:
def tokenize_function(texts):
    return tokenizer(texts, padding=True, truncation=True,return_tensors='pt')

train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)

In [22]:

# Access tokenized input IDs and attention masks
print(train_encodings['input_ids'])
print(train_encodings['attention_mask'])


tensor([[  101,  3103,  9316,  ...,     0,     0,     0],
        [  101,  7160, 27729,  ...,     0,     0,     0],
        [  101,  1017,  2497,  ...,     0,     0,     0],
        ...,
        [  101, 13426,  2075,  ...,     0,     0,     0],
        [  101,  3968, 20668,  ...,     0,     0,     0],
        [  101,  2572, 29378,  ...,     0,     0,     0]])
tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])


In [23]:
import torch
for key, val in train_encodings.items():
    print({key: torch.tensor(val)})

{'input_ids': tensor([[  101,  3103,  9316,  ...,     0,     0,     0],
        [  101,  7160, 27729,  ...,     0,     0,     0],
        [  101,  1017,  2497,  ...,     0,     0,     0],
        ...,
        [  101, 13426,  2075,  ...,     0,     0,     0],
        [  101,  3968, 20668,  ...,     0,     0,     0],
        [  101,  2572, 29378,  ...,     0,     0,     0]])}
{'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])}
{'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}


<ipython-input-23-99d854d5c539>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  print({key: torch.tensor(val)})


In [24]:
import torch

class ProductDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)


# Create datasets
train_dataset = ProductDataset(train_encodings, train_labels)
val_dataset = ProductDataset(val_encodings, val_labels)


In [25]:
train_dataset

In [26]:
len(train_labels)

8001

In [40]:
from transformers import BertForSequenceClassification, Trainer, TrainingArguments

# Load the model
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(train_labels))

# Set up training arguments
training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy='epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=10,
    weight_decay=0.01,
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

# Train the model
trainer.train()


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
<ipython-input-24-2058d511df7b>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}


<ipython-input-24-2058d511df7b>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
<ipython-input-24-2058d511df7b>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
<ipython-input-24-2058d511df7b>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
<ipython-input-24-2058d511df7b>:9: UserWarning: To copy construct from a 

TrainOutput(global_step=10010, training_loss=3.5011844061471367, metrics={'train_runtime': 1612.1246, 'train_samples_per_second': 49.63, 'train_steps_per_second': 6.209, 'total_flos': 2864498080707900.0, 'train_loss': 3.5011844061471367, 'epoch': 10.0})

In [41]:
# Save the model and tokenizer
trainer.save_model('./saved_model')  # Saves the model, configuration, and tokenizer


In [42]:
# Also save the tokenizer explicitly
tokenizer.save_pretrained('./saved_model')

('./saved_model/tokenizer_config.json',
 './saved_model/special_tokens_map.json',
 './saved_model/vocab.txt',
 './saved_model/added_tokens.json')

In [43]:
trainer.evaluate(val_dataset)

<ipython-input-24-2058d511df7b>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}


{'eval_loss': 3.683816909790039,
 'eval_runtime': 7.4214,
 'eval_samples_per_second': 269.626,
 'eval_steps_per_second': 33.821,
 'epoch': 10.0}

In [44]:
trainer.predict(val_dataset)[1]

<ipython-input-24-2058d511df7b>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}


array([923, 938, 769, ..., 297, 830, 921])

In [45]:
from transformers import BertForSequenceClassification, BertTokenizer

# Load the model and tokenizer
model = BertForSequenceClassification.from_pretrained('./saved_model')
tokenizer = BertTokenizer.from_pretrained('./saved_model')

# Set the model to evaluation mode
model.eval()


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

In [46]:
def predict(texts):
    # Tokenize the input text
    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')

    # Make predictions
    with torch.no_grad():
        outputs = model(**inputs)

    # Get the predicted class
    predictions = torch.argmax(outputs.logits, dim=-1)

    return predictions

# Example usage
texts = ["Glow-in-the-Dark Frisbee Disc"]
predictions = predict(texts)

# Map predictions back to label names if needed
predicted_labels = [label_encoder.inverse_transform([pred.item()])[0] for pred in predictions]
print(predicted_labels)


[nan]


In [53]:
def predict(texts):
    # Tokenize the input text
    inputs = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')

    # Make predictions
    with torch.no_grad():
        outputs = model(**inputs)

    # Get the predicted class
    predictions = torch.argmax(outputs.logits, dim=-1)

    return predictions

# Example usage
texts = ["Giant Coloring Book with Stickers"]
predictions = predict(texts)
predictions

tensor([556])

In [54]:
print(label_to_category[556])

Toys & Games | Arts & Crafts
